"""'Share with accountant' summary. Built by code from the session, not by the model, so every
statement in it is traceable to the validator, the official rules or the proposed fix."""

from datetime import UTC, datetime

from facturaguard.rules.index import rule_text

T = {
    "en": {
        "title": "FacturaGuard check: summary for your accountant",
        "file": "File", "checked": "Checked", "source": "Source",
        "verdict": "Validator verdict", "valid": "VALID: passes RO_CIUS 1.0.9 checks",
        "invalid": "INVALID: ANAF would reject this invoice",
        "errors": "Errors found", "rule": "Rule", "official": "Official rule text",
        "plain": "In plain words", "fix_hint": "How to fix",
        "fix": "Proposed correction", "status": "Status", "after": "After the correction",
        "remaining": "Remaining errors", "none": "none",
        "questions": "Questions for the business",
        "diff": "Changes made to the XML", "pdf_note": "Built from a PDF; fields were extracted "
        "by AI and checked against the PDF text.", "ungrounded": "Values not found in the PDF "
        "text (please verify)",
        "footer": "Generated by FacturaGuard. Validation uses ANAF's CIUS-RO 1.0.9 Schematron "
        "and UBL 2.1 XSD. AI explanations and fixes are suggestions; the validator decides "
        "validity. Please review before sending to ANAF.",
    },
    "ro": {
        "title": "Verificare FacturaGuard: rezumat pentru contabil",
        "file": "Fișier", "checked": "Verificat", "source": "Sursă",
        "verdict": "Rezultatul validării", "valid": "VALIDĂ: trece verificările RO_CIUS 1.0.9",
        "invalid": "INVALIDĂ: ANAF ar respinge această factură",
        "errors": "Erori găsite", "rule": "Regula", "official": "Textul oficial al regulii",
        "plain": "Pe scurt", "fix_hint": "Cum se corectează",
        "fix": "Corectură propusă", "status": "Stare", "after": "După corectură",
        "remaining": "Erori rămase", "none": "niciuna",
        "questions": "Întrebări pentru firmă",
        "diff": "Modificări în XML", "pdf_note": "Generat dintr-un PDF; câmpurile au fost "
        "extrase cu AI și verificate față de textul PDF.", "ungrounded": "Valori negăsite în "
        "textul PDF (vă rugăm verificați)",
        "footer": "Generat de FacturaGuard. Validarea folosește Schematron-ul CIUS-RO 1.0.9 al "
        "ANAF și XSD UBL 2.1. Explicațiile și corecturile AI sunt sugestii; validatorul decide "
        "validitatea. Verificați înainte de trimiterea la ANAF.",
    },
}


def accountant_summary(session: dict, lang: str = "en") -> str:
    t = T[lang]
    v = session.get("validation") or {}
    explanations = {e["rule_id"]: e for e in (session.get("explain") or {})
                    .get("explanations", []) if e.get("source") == "model"}
    lines = [
        f"# {t['title']}", "",
        f"- **{t['file']}:** {session.get('file_name', '')}",
        f"- **{t['checked']}:** {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}",
        f"- **{t['source']}:** {session.get('source', 'xml').upper()}",
        f"- **{t['verdict']}:** {t['valid'] if v.get('valid') else t['invalid']}", "",
    ]
    if session.get("source") == "pdf":
        lines += [f"_{t['pdf_note']}_", ""]
        if session.get("ungrounded"):
            lines.append(f"**{t['ungrounded']}:**")
            lines += [f"- `{u['field']}` = {u['value']}" for u in session["ungrounded"]]
            lines.append("")

    seen, errors = set(), []
    for i in v.get("issues", []):
        key = (i["rule_id"], i["message"])
        if i["severity"] == "fatal" and key not in seen:
            seen.add(key)
            errors.append(i)
    if errors:
        lines += [f"## {t['errors']} ({len(errors)})", ""]
        for n, i in enumerate(errors, 1):
            rt = rule_text(i["rule_id"])
            official = rt.text(lang) if rt else i["message"]
            lines.append(f"### {n}. {t['rule']} {i['rule_id']}")
            lines.append(f"- **{t['official']}:** {official}")
            ex = explanations.get(i["rule_id"])
            if ex and ex.get("what_is_wrong"):
                lines.append(f"- **{t['plain']}:** {ex['what_is_wrong']}")
            if ex and ex.get("how_to_fix"):
                lines.append(f"- **{t['fix_hint']}:** {ex['how_to_fix']}")
            lines.append("")

    repair = session.get("repair")
    if repair:
        final = repair.get("final") or {}
        remaining = sorted({i["rule_id"] for i in final.get("issues", [])
                            if i["severity"] == "fatal"})
        lines += [f"## {t['fix']}", "",
                  f"- **{t['status']}:** {repair.get('status')}",
                  f"- **{t['after']}:** {t['valid'] if final.get('valid') else t['invalid']}",
                  f"- **{t['remaining']}:** {', '.join(remaining) or t['none']}"]
        if repair.get("summary"):
            lines.append(f"- {repair['summary']}")
        lines.append("")
        if repair.get("needs_input"):
            lines += [f"### {t['questions']}", ""]
            lines += [f"- {q.get('field', '')}: {q.get('question', '')}"
                      for q in repair["needs_input"]]
            lines.append("")
        if repair.get("diff"):
            lines += [f"### {t['diff']}", "", "```diff", repair["diff"].rstrip(), "```", ""]

    lines += ["---", f"_{t['footer']}_", ""]
    return "\n".join(lines)
